language: "php"

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script:
- "phpunit --testsuite=Tests --coverage-text --coverage-clover build/logs/clover.xml"